version: '4.33.1'

services:
  postgres:
    restart: always
    container_name: loja_virtual_db
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=loja_virtual_database